#!/bin/python3

import math
import os
import random
import re
import sys

num = int(input())
# Complete the factorial function below.

def fact(n):  
   if n == 1:  
       return n  
   else:  
       return n*fact(n-1)  
# check is the number is negative  
if num < 0:  
   print("Sorry, factorial does not exist for negative numbers")  
elif num == 0:  
   print("The factorial of 0 is 1")  
else:  
   print(fact(num)) 
